sudo: required
language: python
python:
  - "3.5"
services:
  - docker
install:
  - docker pull jfloff/alpine-python:latest-slim
  - docker build -t misc-bot .
  - docker run -td misc-bot python3 run.py --dev
script:
  - docker ps | grep misc-bot
